const map=L.map('map',{zoomControl:true}).setView([37.40,140.30],9);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
let incident=null,incidentMarker=null,routeLayer=null,roadTimes={},roadDistances={};
const hospitalLayers=new Map();
const HELIPORTS={
"福島県立医科大学附属病院":{type:"onsite",place:"敷地内ヘリポート",km:0.5,transfer:"院内患者搬送車又は消防署救急車"},
"福島赤十字病院":{type:"onsite",place:"敷地内ヘリポート",km:0.1,transfer:"院内ストレッチャー"},
"太田西ノ内病院":{type:"offsite",place:"郡山河川防災ステーション",km:5.0,transfer:"院内救急車"},
"白河厚生総合病院":{type:"onsite",place:"敷地内ヘリポート",km:0.2,transfer:"院内救急車又は消防署救急車"},
"会津中央病院":{type:"onsite",place:"敷地内ヘリポート",km:0.3,transfer:"院内救急車"},
"福島県立南会津病院":{type:"adjacent",place:"南会津病院場外",km:0.1,transfer:"院内ストレッチャー又は消防署救急車"},
"南相馬市立総合病院":{type:"onsite",place:"敷地内ヘリポート",km:0.1,transfer:"院内ストレッチャー"},
"いわき市医療センター":{type:"onsite",place:"敷地内ヘリポート",km:0.1,transfer:"院内ストレッチャー"}
};
function heliInfo(h){return HELIPORTS[h.name]||null}
function heliLabel(h){const x=heliInfo(h);return x?(x.type==="onsite"?"🚁 敷地内":x.type==="adjacent"?"🚁 病院場外":"🚁 近隣"+x.km+"km"):"🚁 公的指定資料で未確認"}
function iconColor(h){return h.critical?'#ef4444':h.disaster?'#facc15':'#3b82f6'}
function visible(h){return (h.critical&&fCritical.checked)||(h.disaster&&fDisaster.checked)||(h.secondary&&fSecondary.checked)}
function catText(h){let x=[];if(h.critical)x.push("救命救急センター");if(h.disaster)x.push("災害拠点病院");if(h.secondary)x.push("二次救急医療機関");return x.join(" / ")}
function addHospitalMarker(h,i){if(h.lat==null||h.lng==null||!visible(h))return false;if(hospitalLayers.has(i))return true;const hi=heliInfo(h),hs=hi?`<br>${heliLabel(h)} ${hi.place}`:"";const m=L.circleMarker([h.lat,h.lng],{radius:h.critical?8:6,color:"#fff",weight:1,fillColor:iconColor(h),fillOpacity:.95}).addTo(map).bindPopup(`<b>${h.name}</b><br>${catText(h)}<br>${h.area}<br>${h.address||""}${hs}`);hospitalLayers.set(i,m);return true}
async function geocodeHospital(h){if(h.lat!=null&&h.lng!=null)return true;try{const r=await fetch(`https://msearch.gsi.go.jp/address-search/AddressSearch?q=${encodeURIComponent(h.address||("福島県 "+h.name))}`);if(!r.ok)throw 0;const j=await r.json();if(!j?.length)throw 0;h.lng=Number(j[0].geometry.coordinates[0]);h.lat=Number(j[0].geometry.coordinates[1]);return Number.isFinite(h.lat)&&Number.isFinite(h.lng)}catch(e){try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=jp&q=${encodeURIComponent(h.name+" "+(h.address||"福島県"))}`,{headers:{"Accept-Language":"ja"}});const j=await r.json();if(!j?.length)return false;h.lat=Number(j[0].lat);h.lng=Number(j[0].lon);return true}catch(e2){return false}}}
async function drawHospitals(){hospitalLayers.forEach(x=>map.removeLayer(x));hospitalLayers.clear();hospitals.forEach((h,i)=>addHospitalMarker(h,i));const targetCount=hospitals.filter(visible).length;status.textContent=`二次救急医療機関をプロット中… ${hospitalLayers.size}/${targetCount}`;const pending=hospitals.map((h,i)=>({h,i})).filter(x=>x.h.lat==null||x.h.lng==null);for(let k=0;k<pending.length;k+=5){await Promise.all(pending.slice(k,k+5).map(async x=>{if(await geocodeHospital(x.h))addHospitalMarker(x.h,x.i)}));status.textContent=`二次救急医療機関をプロット中… ${hospitalLayers.size}/${targetCount}`}status.textContent=hospitalLayers.size===targetCount?`二次救急医療機関${targetCount}施設を地図上にプロットしました。`:`${hospitalLayers.size}/${targetCount}施設をプロットしました。`;if(hospitalLayers.size>1&&!incident){const pts=[];hospitalLayers.forEach(m=>pts.push(m.getLatLng()));map.fitBounds(L.latLngBounds(pts),{padding:[20,20]})}renderResults()}
drawHospitals();
function setIncident(lat,lng){incident={lat,lng};if(incidentMarker)map.removeLayer(incidentMarker);incidentMarker=L.marker([lat,lng],{draggable:true}).addTo(map).bindPopup("発災地点").openPopup();incidentMarker.on('dragend',e=>{const p=e.target.getLatLng();setIncident(p.lat,p.lng)});incidentText.textContent=`緯度 ${lat.toFixed(5)} / 経度 ${lng.toFixed(5)}`;renderResults()}
map.on('click',e=>setIncident(e.latlng.lat,e.latlng.lng));map.on('contextmenu',e=>setIncident(e.latlng.lat,e.latlng.lng));
const FUKUSHIMA_BOUNDS={west:139.10,east:141.12,south:36.72,north:38.02};
function inFukushimaBounds(lat,lng){return Number.isFinite(lat)&&Number.isFinite(lng)&&lng>=FUKUSHIMA_BOUNDS.west&&lng<=FUKUSHIMA_BOUNDS.east&&lat>=FUKUSHIMA_BOUNDS.south&&lat<=FUKUSHIMA_BOUNDS.north}
function isFukushimaNominatimHit(x){const a=x.address||{},text=[x.display_name,a.state,a.province,a.region,a.county].filter(Boolean).join(" ");return text.includes("福島県")||text.includes("Fukushima")}
function candidateKey(x){return `${Number(x.lat).toFixed(5)},${Number(x.lon).toFixed(5)}`}
async function nominatimSearch(q){const viewbox=`${FUKUSHIMA_BOUNDS.west},${FUKUSHIMA_BOUNDS.north},${FUKUSHIMA_BOUNDS.east},${FUKUSHIMA_BOUNDS.south}`;const qs=new URLSearchParams({format:"json",addressdetails:"1",namedetails:"1",limit:"20",countrycodes:"jp",viewbox,bounded:"1",q});const r=await fetch(`https://nominatim.openstreetmap.org/search?${qs.toString()}`,{headers:{"Accept-Language":"ja"}});if(!r.ok)throw 0;return (await r.json()).filter(x=>{const lat=Number(x.lat),lng=Number(x.lon);return inFukushimaBounds(lat,lng)&&isFukushimaNominatimHit(x)})}
async function gsiSearch(q){const r=await fetch(`https://msearch.gsi.go.jp/address-search/AddressSearch?q=${encodeURIComponent(q.startsWith("福島県")?q:"福島県"+q)}`);if(!r.ok)throw 0;const j=await r.json();return (j||[]).map(x=>{const c=x.geometry?.coordinates||[],lat=Number(c[1]),lon=Number(c[0]),title=x.properties?.title||q;return{lat:String(lat),lon:String(lon),name:title,namedetails:{name:title},display_name:title,address:{state:"福島県"},_source:"gsi"}}).filter(x=>inFukushimaBounds(Number(x.lat),Number(x.lon)))}
async function searchAddress(){const q=addressInput.value.trim(),box=searchCandidates;if(!q){alert("福島県内の住所、病院名、店舗名、施設名などを入力してください。");return}addressBtn.disabled=true;status.textContent="福島県内を検索中…";box.style.display="none";try{const nq=q.includes("福島県")?q:`福島県 ${q}`;const [n1,n2,g]=await Promise.allSettled([nominatimSearch(nq),nominatimSearch(q),gsiSearch(q)]);const merged=[];for(const r of [n1,n2,g])if(r.status==="fulfilled")merged.push(...r.value);const seen=new Set();const ranked=merged.filter(x=>{const k=candidateKey(x);if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>{const an=(a.namedetails?.name||a.name||"").toLowerCase(),bn=(b.namedetails?.name||b.name||"").toLowerCase(),qq=q.toLowerCase();return (an===qq?0:an.includes(qq)?1:2)-(bn===qq?0:bn.includes(qq)?1:2)}).slice(0,10);if(!ranked.length){status.textContent="福島県内に該当地点が見つかりません。住所を詳しくするか、施設の正式名称で検索してください。";return}box.innerHTML=ranked.map((x,i)=>`<div class="candidate" data-candidate="${i}"><div class="ctitle">${x.namedetails?.name||x.name||(x.display_name||"").split(",")[0]}</div><div class="cmeta">${x.display_name||"福島県"}</div></div>`).join("");box.style.display="block";status.textContent=`福島県内で${ranked.length}件の候補が見つかりました。`;box.querySelectorAll(".candidate").forEach(el=>el.onclick=()=>{const hit=ranked[Number(el.dataset.candidate)],lat=Number(hit.lat),lng=Number(hit.lon),title=hit.namedetails?.name||hit.name||(hit.display_name||"").split(",")[0]||q;if(!inFukushimaBounds(lat,lng)){status.textContent="福島県外の候補は設定できません。";return}setIncident(lat,lng);map.setView([lat,lng],14);incidentText.innerHTML=`<b>${title}</b><br>${hit.display_name||"福島県"}<br>緯度 ${lat.toFixed(5)} / 経度 ${lng.toFixed(5)}`;addressInput.value=title;box.style.display="none";status.textContent="発災地点を設定しました。"})}catch(e){status.textContent="地点検索に失敗しました。"}finally{addressBtn.disabled=false}}
addressBtn.onclick=searchAddress;addressInput.addEventListener("keydown",e=>{if(e.key==="Enter")searchAddress()});
geoBtn.onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{setIncident(p.coords.latitude,p.coords.longitude);map.setView([p.coords.latitude,p.coords.longitude],12)},()=>alert("現在地を取得できませんでした。"));
clearBtn.onclick=()=>{incident=null;if(incidentMarker)map.removeLayer(incidentMarker);incidentMarker=null;incidentText.textContent="未設定";roadTimes={};roadDistances={};if(routeLayer)map.removeLayer(routeLayer);renderResults()};
[fCritical,fDisaster,fSecondary].forEach(x=>x.onchange=()=>drawHospitals());[airSpeed,airOverhead].forEach(x=>x.oninput=renderResults);sortMode.onchange=renderResults;routeDirection.onchange=()=>{roadTimes={};roadDistances={};renderResults()};
function hav(a,b){if(!a||b.lat==null||b.lng==null)return null;const R=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lng-a.lng),z=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(z))}
function heliTransferMinutes(h){const x=heliInfo(h);if(!x)return null;if(x.type==="onsite"||x.type==="adjacent")return 2;return Math.max(5,Math.round(x.km/30*60)+3)}
function airMinutes(km,h){if(km==null)return null;const transfer=heliTransferMinutes(h);if(transfer==null)return null;return km/(Number(airSpeed.value)||220)*60+(Number(airOverhead.value)||0)+transfer}
function renderResults(){let arr=hospitals.map((h,i)=>({h,i,dist:incident?hav(incident,h):null,road:roadTimes[i],air:incident?airMinutes(hav(incident,h),h):null})).filter(x=>visible(x.h));if(incident){const mode=sortMode.value;arr.sort((a,b)=>mode==="road"?(a.road??1e9)-(b.road??1e9):mode==="air"?(a.air??1e9)-(b.air??1e9):(a.dist??1e9)-(b.dist??1e9))}else{arr.sort((a,b)=>(a.h.ambulance_rank??999)-(b.h.ambulance_rank??999))}hospitalCount.textContent=arr.length;results.innerHTML=arr.map(x=>{const hi=heliInfo(x.h),hd=hi?`${heliLabel(x.h)}（${hi.place}・病院まで${hi.km}km）`:`${heliLabel(x.h)} ※空路時間は算出しません`;return `<div class="hospital" data-i="${x.i}"><div class="name">${x.h.name}</div><div class="meta">${catText(x.h)} ・ ${x.h.area}<br>${x.h.address||""}${x.dist!=null?" ・ 直線 "+x.dist.toFixed(1)+" km":""}<br>${hd}</div><div class="times"><span class="pill road">陸路 ${x.road!=null?Math.round(x.road)+"分"+(roadDistances[x.i]!=null?" / "+roadDistances[x.i].toFixed(1)+"km":""):"未計算"}</span><span class="pill air">空路 ${x.air!=null?"約"+Math.round(x.air)+"分":"対象外/未確認"}</span></div></div>`}).join("");document.querySelectorAll(".hospital").forEach(el=>el.onclick=async()=>{const i=Number(el.dataset.i),h=hospitals[i];if(incident)return showRoute(i);if(h.lat==null)await geocodeHospital(h);if(h.lat!=null){map.setView([h.lat,h.lng],13);addHospitalMarker(h,i);hospitalLayers.get(i)?.openPopup()}})}
async function fetchRouteTime(x){const h=x.h,rev=routeDirection.value==="hospitalToIncident",c1=rev?`${h.lng},${h.lat}`:`${incident.lng},${incident.lat}`,c2=rev?`${incident.lng},${incident.lat}`:`${h.lng},${h.lat}`;const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${c1};${c2}?overview=false&steps=false`),j=await r.json(),route=j.routes?.[0];if(!route)throw 0;return{minutes:route.duration/60,km:route.distance/1000}}
async function calcRoad(){if(!incident){alert("先に発災地点を指定してください。");return}roadTimes={};roadDistances={};let raw=hospitals.map((h,i)=>({h,i})).filter(x=>visible(x.h));status.textContent="病院位置を確認中…";for(let k=0;k<raw.length;k+=5)await Promise.all(raw.slice(k,k+5).map(async x=>{if(x.h.lat==null&&await geocodeHospital(x.h))addHospitalMarker(x.h,x.i)}));let targets=raw.filter(x=>x.h.lat!=null).map(x=>({...x,dist:hav(incident,x.h)})).sort((a,b)=>a.dist-b.dist);if(roadLimit.value!=="all")targets=targets.slice(0,Number(roadLimit.value));let done=0,failed=0;for(let k=0;k<targets.length;k+=4){await Promise.all(targets.slice(k,k+4).map(async x=>{try{const rr=await fetchRouteTime(x);roadTimes[x.i]=rr.minutes;roadDistances[x.i]=rr.km;done++}catch(e){failed++}}));status.textContent=`陸路計算中… ${Math.min(k+4,targets.length)}/${targets.length}`;renderResults()}status.textContent=failed?`${done}施設を計算（${failed}施設失敗）`:`${done}施設の陸路距離・所要時間を計算しました。`;renderResults()}
calcBtn.onclick=calcRoad;
async function showRoute(i){const h=hospitals[i];if(h.lat==null&&!await geocodeHospital(h)){status.textContent="病院位置を取得できませんでした。";return}if(routeLayer)map.removeLayer(routeLayer);const rev=routeDirection.value==="hospitalToIncident",from=rev?`${h.lng},${h.lat}`:`${incident.lng},${incident.lat}`,to=rev?`${incident.lng},${incident.lat}`:`${h.lng},${h.lat}`;try{const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${from};${to}?overview=full&geometries=geojson`),j=await r.json(),route=j.routes?.[0];if(!route)throw 0;routeLayer=L.geoJSON(route.geometry,{style:{weight:5,opacity:.75}}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[30,30]});roadTimes[i]=route.duration/60;roadDistances[i]=route.distance/1000;renderResults();status.textContent=`${h.name}: 陸路 約${Math.round(roadTimes[i])}分 / ${roadDistances[i].toFixed(1)} km`}catch(e){status.textContent="ルート取得に失敗しました。"}}
renderResults();