// 福島県内の発災地点検索を補強：県内の名称付きPOI全般＋電柱・鉄塔を検索
const IMPORTANT_SPECIAL_PLACES=[
{name:"郡山消防署",aliases:["郡山消防署","消防本部郡山消防署","koriyama fire station","koriyama fire department","koriyama shobosho","koriyama shoubousho"],address:"福島県郡山市堂前町5-16",group:"koriyama-fire"},
{name:"郡山消防署 大槻基幹分署",aliases:["大槻基幹分署","郡山消防署大槻基幹分署","otsuki fire station","otsuki branch fire station","otsuki bunkasho"],address:"福島県郡山市大槻町字中前田15-2",group:"koriyama-fire"},
{name:"郡山消防署 喜久田基幹分署",aliases:["喜久田基幹分署","郡山消防署喜久田基幹分署","kikuta fire station","kikuta branch fire station","kikuta bunkasho"],address:"福島県郡山市喜久田町卸一丁目134-1",group:"koriyama-fire"},
{name:"郡山消防署 熱海分署",aliases:["熱海分署","郡山消防署熱海分署","atami fire station","atami branch fire station","atami bunkasho"],address:"福島県郡山市熱海町熱海二丁目65",group:"koriyama-fire"},
{name:"郡山消防署 日和田分署",aliases:["日和田分署","郡山消防署日和田分署","hiwada fire station","hiwada branch fire station","hiwada bunkasho"],address:"福島県郡山市日和田町字山ノ井1-1",group:"koriyama-fire"},
{name:"郡山消防署 田村分署",aliases:["田村分署","郡山消防署田村分署","tamura fire station","tamura branch fire station","tamura bunkasho"],address:"福島県郡山市田村町岩作字穂多礼57-5",group:"koriyama-fire"},
{name:"郡山消防署 安積分署",aliases:["安積分署","郡山消防署安積分署","asaka fire station","asaka branch fire station","asaka bunkasho"],address:"福島県郡山市安積二丁目354",group:"koriyama-fire"},
{name:"郡山消防署 湖南分署",aliases:["湖南分署","郡山消防署湖南分署","konan fire station","konan branch fire station","konan bunkasho"],address:"福島県郡山市湖南町三代字原木390-8",group:"koriyama-fire"},
{name:"郡山消防署 中田分署",aliases:["中田分署","郡山消防署中田分署","郡山 中田分署","nakata fire station","nakata branch fire station","nakata bunkasho"],address:"福島県郡山市中田町下枝字柏田202-1",group:"koriyama-fire"},
{name:"郡山消防署 富久山分署",aliases:["富久山分署","郡山消防署富久山分署","fukuyama fire station","fukuyama branch fire station","fukuyama bunkasho"],address:"福島県郡山市富久山町八山田字経堂52-1",group:"koriyama-fire"},
{name:"郡山消防署 針生救急所",aliases:["針生救急所","郡山消防署針生救急所","hariu ambulance station","hariu emergency station","hariu kyukyusho"],address:"福島県郡山市大槻町字笹ノ台34-1",group:"koriyama-fire"}
];
const SEARCH_SYNONYMS=[
{re:/\b(branch\s*fire\s*station|bunkasho)\b/ig,jp:"分署"},{re:/\b(fire\s*station|fire\s*department|shobosho|shoubousho)\b/ig,jp:"消防署"},{re:/\b(police\s*station|police)\b/ig,jp:"警察署"},{re:/\b(koban|police\s*box)\b/ig,jp:"交番"},{re:/\b(clinic|medical\s*clinic)\b/ig,jp:"クリニック"},{re:/\b(hospital)\b/ig,jp:"病院"},{re:/\b(pharmacy|drugstore)\b/ig,jp:"薬局"},{re:/\b(hair\s*salon|beauty\s*salon|beautician|barber)\b/ig,jp:"美容院"},{re:/\b(restaurant)\b/ig,jp:"レストラン"},{re:/\b(cafe|coffee\s*shop)\b/ig,jp:"カフェ"},{re:/\b(convenience\s*store)\b/ig,jp:"コンビニ"},{re:/\b(supermarket)\b/ig,jp:"スーパー"},{re:/\b(school)\b/ig,jp:"学校"},{re:/\b(station|railway\s*station)\b/ig,jp:"駅"},{re:/\b(utility\s*pole|power\s*pole|telephone\s*pole|electric\s*pole)\b/ig,jp:"電柱"}
];
function normalizePlaceText(s){return String(s||"").replace(/[\s　・‐－―ー]/g,"").toLowerCase()}
function escapeRegExp(s){return String(s||"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function translatedQueries(q){const out=[q];for(const x of SEARCH_SYNONYMS){const t=q.replace(x.re,x.jp);if(t!==q)out.push(t)}const n=normalizePlaceText(q);if(["koriyamafirestation","koriyamafiredepartment","koriyamashobosho","koriyamashoubousho"].includes(n))out.push("郡山消防署");return[...new Set(out)]}
function poiCategory(t={}){if(t.power==="pole")return"電柱";if(t.power==="tower")return"送電鉄塔";if(t.amenity==="fire_station")return"消防";if(t.amenity==="police")return"警察";if(t.shop==="hairdresser"||t.shop==="beauty")return"美容院";if(t.amenity)return t.amenity;if(t.shop)return"店舗";if(t.tourism)return"観光施設";if(t.leisure)return"レジャー";if(t.office)return"事業所";if(t.man_made)return"施設";return"施設"}
function elementToCandidate(e,q){const t=e.tags||{},lat=Number(e.lat??e.center?.lat),lon=Number(e.lon??e.center?.lon);if(!inFukushimaBounds(lat,lon))return null;const name=t.name||t["name:ja"]||t["name:en"]||t["name:ja-Latn"]||t.ref||t["ref:JP"]||t["operator:ref"]||q;const ref=t.ref||t["ref:JP"]||t["operator:ref"]||"";const addr=[t["addr:province"]||"福島県",t["addr:city"],t["addr:suburb"],t["addr:quarter"],t["addr:street"],t["addr:housenumber"]].filter(Boolean).join("");const label=[name,ref&&ref!==name?`番号 ${ref}`:"",poiCategory(t),addr].filter(Boolean).join(" ・ ");return{lat:String(lat),lon:String(lon),name,namedetails:{name},display_name:label,address:{state:"福島県"},_source:"overpass",_priority:0}}
async function searchAllFukushimaPOI(q){const safe=escapeRegExp(q.trim()).replace(/\\ /g,".*");if(!safe)return[];const query=`[out:json][timeout:18];area["ISO3166-2"="JP-07"]["boundary"="administrative"]->.a;(nwr(area.a)["name"~"${safe}",i];nwr(area.a)["name:ja"~"${safe}",i];nwr(area.a)["name:en"~"${safe}",i];nwr(area.a)["name:ja-Latn"~"${safe}",i];nwr(area.a)["ref"~"${safe}",i];nwr(area.a)["power"="pole"]["ref"~"${safe}",i];nwr(area.a)["power"="tower"]["ref"~"${safe}",i];);out center tags 60;`;try{const r=await fetch("https://overpass-api.de/api/interpreter",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:"data="+encodeURIComponent(query)});if(!r.ok)throw 0;const j=await r.json();return(j.elements||[]).map(e=>elementToCandidate(e,q)).filter(Boolean)}catch(e){return[]}}
async function searchKnownSpecialPlaces(q){const nq=normalizePlaceText(q),isGroup=["郡山消防署","消防本部郡山消防署","koriyama fire station","koriyama fire department","koriyama shobosho","koriyama shoubousho"].some(x=>normalizePlaceText(x)===nq);const matched=isGroup?IMPORTANT_SPECIAL_PLACES.filter(p=>p.group==="koriyama-fire"):IMPORTANT_SPECIAL_PLACES.filter(p=>p.aliases.some(a=>{const na=normalizePlaceText(a);return na===nq||na.includes(nq)||nq.includes(na)}));const out=[];await Promise.all(matched.map(async p=>{try{const r=await fetch(`https://msearch.gsi.go.jp/address-search/AddressSearch?q=${encodeURIComponent(p.address)}`);if(!r.ok)return;const j=await r.json(),c=j?.[0]?.geometry?.coordinates||[],lon=Number(c[0]),lat=Number(c[1]);if(inFukushimaBounds(lat,lon))out.push({lat:String(lat),lon:String(lon),name:p.name,namedetails:{name:p.name},display_name:`${p.name} ・ ${p.address}`,address:{state:"福島県"},_source:"special",_priority:-2})}catch(e){}}));return out}
searchAddress=async function(){const q=addressInput.value.trim(),box=searchCandidates;if(!q){alert("福島県内の住所・施設名・店舗名・電柱番号などを入力してください。");return}addressBtn.disabled=true;status.textContent="福島県内を検索中…";box.style.display="none";try{const qs=translatedQueries(q),tasks=[searchKnownSpecialPlaces(q)];for(const x of qs){tasks.push(searchAllFukushimaPOI(x));tasks.push(nominatimSearch(x.includes("福島県")?x:`福島県 ${x}`));tasks.push(nominatimSearch(x));if(/[ぁ-んァ-ヶ一-龠]/.test(x))tasks.push(gsiSearch(x))}const settled=await Promise.allSettled(tasks),merged=[];for(const r of settled)if(r.status==="fulfilled")merged.push(...r.value);const seen=new Set(),qq=normalizePlaceText(q),isKoriyamaFire=["郡山消防署","消防本部郡山消防署","koriyama fire station","koriyama fire department","koriyama shobosho","koriyama shoubousho"].some(x=>normalizePlaceText(x)===qq);const ranked=merged.filter(x=>{const k=candidateKey(x);if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>{const ap=a._priority??1,bp=b._priority??1;if(ap!==bp)return ap-bp;const an=normalizePlaceText(a.namedetails?.name||a.name||""),bn=normalizePlaceText(b.namedetails?.name||b.name||""),as=an===qq?0:an.includes(qq)?1:2,bs=bn===qq?0:bn.includes(qq)?1:2;return as-bs}).slice(0,isKoriyamaFire?20:25);if(!ranked.length){status.textContent="福島県内に該当地点が見つかりません。名称・住所・電柱番号などを詳しく入力してください。";return}box.innerHTML=ranked.map((x,i)=>`<div class="candidate" data-candidate="${i}"><div class="ctitle">${x.namedetails?.name||x.name||(x.display_name||"").split(",")[0]}</div><div class="cmeta">${x.display_name||"福島県"}</div></div>`).join("");box.style.display="block";status.textContent=isKoriyamaFire?`郡山消防署と管内の分署・救急所を表示しています（${ranked.length}件）。`:`福島県内で${ranked.length}件の候補が見つかりました。`;box.querySelectorAll(".candidate").forEach(el=>el.onclick=()=>{const hit=ranked[Number(el.dataset.candidate)],lat=Number(hit.lat),lng=Number(hit.lon),title=hit.namedetails?.name||hit.name||(hit.display_name||"").split(",")[0]||q;if(!inFukushimaBounds(lat,lng)){status.textContent="福島県外の候補は設定できません。";return}setIncident(lat,lng);map.setView([lat,lng],16);incidentText.innerHTML=`<b>${title}</b><br>${hit.display_name||"福島県"}<br>緯度 ${lat.toFixed(5)} / 経度 ${lng.toFixed(5)}`;addressInput.value=title;box.style.display="none";status.textContent="発災地点を設定しました。"})}catch(e){status.textContent="地点検索に失敗しました。"}finally{addressBtn.disabled=false}};
addressBtn.onclick=searchAddress;
