// 検索高速化レイヤー: キャッシュ + 軽量検索優先 + Overpass遅延フォールバック + 予測検索
const FAST_SEARCH_CACHE_KEY='fukushima-disaster-map-search-v2';
const FAST_SEARCH_TTL=7*24*60*60*1000;
function fastCacheRead(q){try{const all=JSON.parse(localStorage.getItem(FAST_SEARCH_CACHE_KEY)||'{}');const x=all[normalizePlaceText(q)];return x&&Date.now()-x.t<FAST_SEARCH_TTL?x.v:null}catch(e){return null}}
function fastCacheWrite(q,v){try{const all=JSON.parse(localStorage.getItem(FAST_SEARCH_CACHE_KEY)||'{}');all[normalizePlaceText(q)]={t:Date.now(),v};const keys=Object.keys(all);if(keys.length>80)keys.sort((a,b)=>all[a].t-all[b].t).slice(0,keys.length-80).forEach(k=>delete all[k]);localStorage.setItem(FAST_SEARCH_CACHE_KEY,JSON.stringify(all))}catch(e){}}
function fastUniqueRank(items,q,limit=40){const seen=new Set();return items.filter(x=>{if(!x)return false;const k=candidateKey(x);if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>{const ap=a._priority??1,bp=b._priority??1;if(ap!==bp)return ap-bp;return partialScore(a,q)-partialScore(b,q)}).slice(0,limit)}
function chooseFastCandidate(hit,q,box){const lat=Number(hit.lat),lng=Number(hit.lon),title=hit.namedetails?.name||hit.name||(hit.display_name||'').split(',')[0]||q;if(!inFukushimaBounds(lat,lng)){status.textContent='福島県外の候補は設定できません。';return}setIncident(lat,lng);map.setView([lat,lng],16);incidentText.innerHTML=`<b>${title}</b><br>${hit.display_name||'福島県'}<br>緯度 ${lat.toFixed(5)} / 経度 ${lng.toFixed(5)}`;addressInput.value=title;box.style.display='none';status.textContent='発災地点を設定しました。'}
function fastRender(ranked,q,box,isKoriyamaFire=false,predictive=false){if(!ranked.length){if(!predictive)status.textContent='福島県内に該当地点が見つかりません。名称の一部・住所などで検索できます。';box.style.display='none';return}box.innerHTML=ranked.map((x,i)=>`<div class="candidate" data-candidate="${i}"><div class="ctitle">${x.namedetails?.name||x.name||(x.display_name||'').split(',')[0]}</div><div class="cmeta">${x.display_name||'福島県'}</div></div>`).join('');box.style.display='block';if(!predictive)status.textContent=isKoriyamaFire?`郡山消防署と管内の分署・救急所を表示しています（${ranked.length}件）。`:`福島県内で${ranked.length}件の候補が見つかりました。`;box.querySelectorAll('.candidate').forEach(el=>el.onclick=()=>chooseFastCandidate(ranked[Number(el.dataset.candidate)],q,box))}
async function fastLightSearch(q,limit=8){const cached=fastCacheRead(q);if(cached?.length)return cached.slice(0,limit);const qs=translatedQueries(q),tasks=[searchKnownSpecialPlaces(q)];for(const x of qs){tasks.push(nominatimSearch(x.includes('福島県')?x:`福島県 ${x}`));if(/[ぁ-んァ-ヶ一-龠]/.test(x))tasks.push(gsiSearch(x))}const settled=await Promise.allSettled(tasks),merged=[];for(const r of settled)if(r.status==='fulfilled')merged.push(...r.value);const ranked=fastUniqueRank(merged,q,limit);if(ranked.length)fastCacheWrite(q,ranked);return ranked}
searchAddress=async function(){const q=addressInput.value.trim(),box=searchCandidates;if(!q){alert('福島県内の住所・施設名・店舗名・電柱番号などを入力してください。');return}addressBtn.disabled=true;box.style.display='none';const cached=fastCacheRead(q);if(cached?.length){fastRender(cached,q,box);addressBtn.disabled=false;status.textContent=`福島県内で${cached.length}件の候補が見つかりました（高速キャッシュ）。`;return}status.textContent='福島県内を高速検索中…';try{let ranked=await fastLightSearch(q,40);const qq=normalizePlaceText(q),isKoriyamaFire=['郡山消防署','消防本部郡山消防署','koriyama fire station','koriyama fire department','koriyama shobosho','koriyama shoubousho'].some(x=>normalizePlaceText(x)===qq);if(ranked.length){fastRender(ranked,q,box,isKoriyamaFire);return}status.textContent='候補を追加検索中…';const qs=translatedQueries(q),heavy=await Promise.allSettled(qs.map(x=>searchAllFukushimaPOI(x))),merged=[];for(const r of heavy)if(r.status==='fulfilled')merged.push(...r.value);ranked=fastUniqueRank(merged,q,isKoriyamaFire?20:40);if(ranked.length)fastCacheWrite(q,ranked);fastRender(ranked,q,box,isKoriyamaFire)}catch(e){status.textContent='地点検索に失敗しました。'}finally{addressBtn.disabled=false}};
addressBtn.onclick=searchAddress;

// Googleマップ風予測検索: 2文字以上、入力停止250ms後に軽量検索だけを実行
let predictiveTimer=null,predictiveSeq=0;
addressInput.setAttribute('autocomplete','off');
addressInput.addEventListener('input',()=>{clearTimeout(predictiveTimer);const q=addressInput.value.trim(),seq=++predictiveSeq;if(q.length<2){searchCandidates.style.display='none';return}const cached=fastCacheRead(q);if(cached?.length){fastRender(cached.slice(0,8),q,searchCandidates,false,true);return}predictiveTimer=setTimeout(async()=>{try{const ranked=await fastLightSearch(q,8);if(seq!==predictiveSeq||addressInput.value.trim()!==q)return;fastRender(ranked,q,searchCandidates,false,true)}catch(e){}},250)});
addressInput.addEventListener('keydown',e=>{if(e.key==='Escape')searchCandidates.style.display='none'});
document.addEventListener('click',e=>{if(e.target!==addressInput&&!searchCandidates.contains(e.target)&&e.target!==addressBtn)searchCandidates.style.display='none'});
