// 検索高速化レイヤー: キャッシュ + 軽量検索優先 + Overpass部分一致 + 予測検索 + 現在地優先 + 種別アイコン
const FAST_SEARCH_CACHE_KEY='fukushima-disaster-map-search-v5';
const FAST_SEARCH_TTL=7*24*60*60*1000;
let fastUserLocation=null,fastLocationRequested=false;
function fastCacheRead(q){try{const all=JSON.parse(localStorage.getItem(FAST_SEARCH_CACHE_KEY)||'{}');const x=all[normalizePlaceText(q)];return x&&Date.now()-x.t<FAST_SEARCH_TTL?x.v:null}catch(e){return null}}
function fastCacheWrite(q,v){try{const all=JSON.parse(localStorage.getItem(FAST_SEARCH_CACHE_KEY)||'{}');all[normalizePlaceText(q)]={t:Date.now(),v};const keys=Object.keys(all);if(keys.length>80)keys.sort((a,b)=>all[a].t-all[b].t).slice(0,keys.length-80).forEach(k=>delete all[k]);localStorage.setItem(FAST_SEARCH_CACHE_KEY,JSON.stringify(all))}catch(e){}}
function fastDistanceKm(a,b,c,d){const R=6371,toRad=x=>x*Math.PI/180,dp=toRad(c-a),dl=toRad(d-b),v=Math.sin(dp/2)**2+Math.cos(toRad(a))*Math.cos(toRad(c))*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(v))}
function fastCandidateDistance(x){if(!fastUserLocation)return Infinity;const lat=Number(x.lat),lon=Number(x.lon);return Number.isFinite(lat)&&Number.isFinite(lon)?fastDistanceKm(fastUserLocation.lat,fastUserLocation.lon,lat,lon):Infinity}
function fastPlaceIcon(x){const s=((x.namedetails?.name||x.name||'')+' '+(x.display_name||'')+' '+(x._searchText||'')).toLowerCase();if(/病院|hospital|医療センター|医療センタ/.test(s))return '🏥';if(/診療所|クリニック|clinic/.test(s))return '🩺';if(/消防|分署|救急所|fire station|fire department/.test(s))return '🚒';if(/警察|交番|駐在所|police|koban/.test(s))return '👮';if(/駅|station|鉄道/.test(s))return '🚉';if(/学校|小学校|中学校|高校|大学|school|university/.test(s))return '🏫';if(/薬局|pharmacy|drugstore/.test(s))return '💊';if(/市役所|町役場|村役場|役所|庁舎|city hall|town hall/.test(s))return '🏛️';if(/空港|airport/.test(s))return '✈️';if(/ヘリポート|heliport/.test(s))return '🚁';if(/コンビニ|スーパー|店舗|store|shop/.test(s))return '🏪';return '📍'}
function requestFastUserLocation(){if(fastLocationRequested||!navigator.geolocation)return;fastLocationRequested=true;navigator.geolocation.getCurrentPosition(p=>{fastUserLocation={lat:p.coords.latitude,lon:p.coords.longitude};const q=addressInput.value.trim();if(q.length>=2){const cached=fastCacheRead(q);if(cached?.length)fastRender(fastUniqueRank(cached,q,8),q,searchCandidates,false,true)}},()=>{}, {enableHighAccuracy:false,timeout:5000,maximumAge:300000})}
function fastUniqueRank(items,q,limit=40){const seen=new Set();return items.filter(x=>{if(!x)return false;const k=candidateKey(x);if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>{const ap=a._priority??1,bp=b._priority??1;if(ap!==bp)return ap-bp;const as=partialScore(a,q),bs=partialScore(b,q);if(as!==bs)return as-bs;return fastCandidateDistance(a)-fastCandidateDistance(b)}).slice(0,limit)}
function chooseFastCandidate(hit,q,box){const lat=Number(hit.lat),lng=Number(hit.lon),title=hit.namedetails?.name||hit.name||(hit.display_name||'').split(',')[0]||q;if(!inFukushimaBounds(lat,lng)){status.textContent='福島県外の候補は設定できません。';return}setIncident(lat,lng);map.setView([lat,lng],16);incidentText.innerHTML=`<b>${fastPlaceIcon(hit)} ${title}</b><br>${hit.display_name||'福島県'}<br>緯度 ${lat.toFixed(5)} / 経度 ${lng.toFixed(5)}`;addressInput.value=title;box.style.display='none';status.textContent='発災地点を設定しました。'}
function fastRender(ranked,q,box,isKoriyamaFire=false,predictive=false){if(!ranked.length){if(!predictive)status.textContent='福島県内に該当地点が見つかりません。名称の一部・住所などで検索できます。';box.style.display='none';return}box.innerHTML=ranked.map((x,i)=>{const d=fastCandidateDistance(x),dist=Number.isFinite(d)?` ・ 現在地から約${d<10?d.toFixed(1):Math.round(d)}km`:'';return `<div class="candidate" data-candidate="${i}" style="display:grid;grid-template-columns:32px 1fr;gap:7px;align-items:center"><div style="font-size:22px;text-align:center">${fastPlaceIcon(x)}</div><div><div class="ctitle">${x.namedetails?.name||x.name||(x.display_name||'').split(',')[0]}</div><div class="cmeta">${x.display_name||'福島県'}${dist}</div></div></div>`}).join('');box.style.display='block';if(!predictive)status.textContent=isKoriyamaFire?`郡山消防署と管内の分署・救急所を表示しています（${ranked.length}件）。`:`福島県内で${ranked.length}件の候補が見つかりました（部分一致対応）。`;box.querySelectorAll('.candidate').forEach(el=>el.onclick=()=>chooseFastCandidate(ranked[Number(el.dataset.candidate)],q,box))}
async function fastLightSearch(q,limit=8){const cached=fastCacheRead(q);if(cached?.length)return fastUniqueRank(cached,q,limit);const qs=translatedQueries(q),tasks=[searchKnownSpecialPlaces(q)];for(const x of qs){tasks.push(nominatimSearch(x.includes('福島県')?x:`福島県 ${x}`));if(/[ぁ-んァ-ヶ一-龠]/.test(x))tasks.push(gsiSearch(x))}const settled=await Promise.allSettled(tasks),merged=[];for(const r of settled)if(r.status==='fulfilled')merged.push(...r.value);const ranked=fastUniqueRank(merged,q,limit);if(ranked.length)fastCacheWrite(q,ranked);return ranked}
async function fastPartialSearch(q,limit=40){const qs=translatedQueries(q),settled=await Promise.allSettled(qs.map(x=>searchAllFukushimaPOI(x))),merged=[];for(const r of settled)if(r.status==='fulfilled')merged.push(...r.value);return fastUniqueRank(merged,q,limit)}
searchAddress=async function(){requestFastUserLocation();const q=addressInput.value.trim(),box=searchCandidates;if(!q){alert('福島県内の住所・施設名・店舗名・電柱番号などを入力してください。');return}addressBtn.disabled=true;box.style.display='none';const cached=fastCacheRead(q);if(cached?.length){const ranked=fastUniqueRank(cached,q,40);fastRender(ranked,q,box);addressBtn.disabled=false;status.textContent=`福島県内で${ranked.length}件の候補が見つかりました（部分一致・高速キャッシュ）。`;return}status.textContent='福島県内を高速検索中…';try{let light=await fastLightSearch(q,40);status.textContent='部分一致の候補を検索中…';let partial=[];try{partial=await fastPartialSearch(q,40)}catch(e){}const ranked=fastUniqueRank([...light,...partial],q,40);if(ranked.length)fastCacheWrite(q,ranked);const qq=normalizePlaceText(q),isKoriyamaFire=['郡山消防署','消防本部郡山消防署','koriyama fire station','koriyama fire department','koriyama shobosho','koriyama shoubousho'].some(x=>normalizePlaceText(x)===qq);fastRender(ranked,q,box,isKoriyamaFire)}catch(e){status.textContent='地点検索に失敗しました。'}finally{addressBtn.disabled=false}};
addressBtn.onclick=searchAddress;
let predictiveTimer=null,predictiveSeq=0;
addressInput.setAttribute('autocomplete','off');
addressInput.addEventListener('focus',requestFastUserLocation,{once:true});
addressInput.addEventListener('input',()=>{requestFastUserLocation();clearTimeout(predictiveTimer);const q=addressInput.value.trim(),seq=++predictiveSeq;if(q.length<2){searchCandidates.style.display='none';return}const cached=fastCacheRead(q);if(cached?.length){fastRender(fastUniqueRank(cached,q,8),q,searchCandidates,false,true);return}predictiveTimer=setTimeout(async()=>{try{const light=await fastLightSearch(q,8);if(seq!==predictiveSeq||addressInput.value.trim()!==q)return;if(light.length)fastRender(light,q,searchCandidates,false,true);const partial=await fastPartialSearch(q,8);if(seq!==predictiveSeq||addressInput.value.trim()!==q)return;const ranked=fastUniqueRank([...light,...partial],q,8);if(ranked.length)fastCacheWrite(q,ranked);fastRender(ranked,q,searchCandidates,false,true)}catch(e){}},300)});
addressInput.addEventListener('keydown',e=>{if(e.key==='Escape')searchCandidates.style.display='none'});
document.addEventListener('click',e=>{if(e.target!==addressInput&&!searchCandidates.contains(e.target)&&e.target!==addressBtn)searchCandidates.style.display='none'});
